apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: contoh-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contoh-replicaset
  template:
    metadata:
      labels:
        app: contoh-replicaset
    spec:
      containers:
        - name: contoh-replicaset
          image: herdanis/simple-service:1.0
          ports:
            - containerPort: 8098
