apiVersion: v1
kind: Pod
metadata:
  name: contoh-multi-container
  labels:
    name: contoh-multi-container
spec:
  containers:
    - name: container-a
      image: herdanis/simple-service:1.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8089
    - name: container-b
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
