apiVersion: v1
kind: ConfigMap
metadata:
  name: contoh-config
data:
  APPS_NAME: contoh-config
  USER_CONFIG: user-dari-config
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
  labels:
    name: pod-configmap
spec:
  containers:
    - name: pod-configmap
      image: herdanis/simple-service:1.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8089
      envFrom:
        - configMapRef:
            name: contoh-config
