apiVersion: v1
kind: Secret
metadata:
  name: contoh-secret
type: Opaque
data:
  password: Y29udG9oCg==
stringData:
  passcode: ini-bukan-password
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  labels:
    name: pod-secret
spec:
  containers:
    - name: pod-secret
      image: herdanis/simple-service:1.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8089
      envFrom:
        - secretRef:
            name: contoh-secret
