apiVersion: v1
kind: Service
metadata:
  name: contoh-nodeport
spec:
  type: NodePort
  selector:
    app: rs-service
  ports:
    - port: 80
      targetPort: 8089
      nodePort: 30000
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rs-service
  template:
    metadata:
      labels:
        app: rs-service
    spec:
      containers:
        - name: rs-service
          image: herdanis/simple-service:1.0
