apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoh-deployment-volume
spec:
  selector:
    matchLabels:
      app: contoh-deployment-volume
  template:
    metadata:
      labels:
        app: contoh-deployment-volume
    spec:
      containers:
        - name: contoh-deployment-volume
          image: herdanis/simple-service:1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8089
          volumeMounts:
            - name: disk
              mountPath: /app/data
      volumes:
        - name: disk
          hostPath:
            path: /home/data-host
