apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-statefullset
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pv-statefullset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: contoh-statefullset
spec:
  selector:
    matchLabels:
      app: contoh-statefullset
  serviceName: svc-statefullset
  replicas: 2
  template:
    metadata:
      labels:
        app: contoh-statefullset
    spec:
      containers:
        - name: contoh-statefullset
          image: herdanis/simple-service:1.0
          ports:
            - containerPort: 8089
          volumeMounts:
            - name: sts
              mountPath: /app/data
  volumeClaimTemplates:
    - metadata:
        name: sts
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
