apiVersion: batch/v1
kind: Job
metadata:
  name: contoh-job
spec:
  ttlSecondsAfterFinished: 100
  completions: 4
  parallelism: 2
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: container-job
          image: nginx
          command: ["curl", "example.com"]
      restartPolicy: Never
