apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: contoh-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-hpa
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hpa
spec:
  selector:
    matchLabels:
      app: deployment-hpa
  template:
    metadata:
      labels:
        app: deployment-hpa
    spec:
      containers:
        - name: deployment-hpa
          image: herdanis/simple-service:1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8089
